// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: coordinator.proto

#include "coordinator.pb.h"
#include "coordinator.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace coordinator {

static const char* FileSystem_method_names[] = {
  "/coordinator.FileSystem/createDir",
  "/coordinator.FileSystem/uploadStripe",
  "/coordinator.FileSystem/downloadStripe",
  "/coordinator.FileSystem/downloadStripeWithHint",
  "/coordinator.FileSystem/deleteStripe",
  "/coordinator.FileSystem/uploadCheck",
  "/coordinator.FileSystem/reportblockupload",
  "/coordinator.FileSystem/listStripe",
  "/coordinator.FileSystem/listAllStripes",
  "/coordinator.FileSystem/transitionup",
  "/coordinator.FileSystem/setplacementpolicy",
};

std::unique_ptr< FileSystem::Stub> FileSystem::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileSystem::Stub> stub(new FileSystem::Stub(channel));
  return stub;
}

FileSystem::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_createDir_(FileSystem_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_uploadStripe_(FileSystem_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_downloadStripe_(FileSystem_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_downloadStripeWithHint_(FileSystem_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deleteStripe_(FileSystem_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_uploadCheck_(FileSystem_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_reportblockupload_(FileSystem_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_listStripe_(FileSystem_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_listAllStripes_(FileSystem_method_names[8], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_transitionup_(FileSystem_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setplacementpolicy_(FileSystem_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FileSystem::Stub::createDir(::grpc::ClientContext* context, const ::coordinator::Path& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_createDir_, context, request, response);
}

void FileSystem::Stub::experimental_async::createDir(::grpc::ClientContext* context, const ::coordinator::Path* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_createDir_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::createDir(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_createDir_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::createDir(::grpc::ClientContext* context, const ::coordinator::Path* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_createDir_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::createDir(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_createDir_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsynccreateDirRaw(::grpc::ClientContext* context, const ::coordinator::Path& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_createDir_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsynccreateDirRaw(::grpc::ClientContext* context, const ::coordinator::Path& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_createDir_, context, request, false);
}

::grpc::Status FileSystem::Stub::uploadStripe(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::coordinator::StripeDetail* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_uploadStripe_, context, request, response);
}

void FileSystem::Stub::experimental_async::uploadStripe(::grpc::ClientContext* context, const ::coordinator::StripeInfo* request, ::coordinator::StripeDetail* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_uploadStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::uploadStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeDetail* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_uploadStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::uploadStripe(::grpc::ClientContext* context, const ::coordinator::StripeInfo* request, ::coordinator::StripeDetail* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_uploadStripe_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::uploadStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeDetail* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_uploadStripe_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeDetail>* FileSystem::Stub::AsyncuploadStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeDetail>::Create(channel_.get(), cq, rpcmethod_uploadStripe_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeDetail>* FileSystem::Stub::PrepareAsyncuploadStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeDetail>::Create(channel_.get(), cq, rpcmethod_uploadStripe_, context, request, false);
}

::grpc::Status FileSystem::Stub::downloadStripe(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::coordinator::StripeDetail* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_downloadStripe_, context, request, response);
}

void FileSystem::Stub::experimental_async::downloadStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeDetail* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_downloadStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::downloadStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeDetail* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_downloadStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::downloadStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeDetail* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_downloadStripe_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::downloadStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeDetail* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_downloadStripe_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeDetail>* FileSystem::Stub::AsyncdownloadStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeDetail>::Create(channel_.get(), cq, rpcmethod_downloadStripe_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeDetail>* FileSystem::Stub::PrepareAsyncdownloadStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeDetail>::Create(channel_.get(), cq, rpcmethod_downloadStripe_, context, request, false);
}

::grpc::Status FileSystem::Stub::downloadStripeWithHint(::grpc::ClientContext* context, const ::coordinator::StripeIdWithHint& request, ::coordinator::StripeLocation* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_downloadStripeWithHint_, context, request, response);
}

void FileSystem::Stub::experimental_async::downloadStripeWithHint(::grpc::ClientContext* context, const ::coordinator::StripeIdWithHint* request, ::coordinator::StripeLocation* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_downloadStripeWithHint_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::downloadStripeWithHint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeLocation* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_downloadStripeWithHint_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::downloadStripeWithHint(::grpc::ClientContext* context, const ::coordinator::StripeIdWithHint* request, ::coordinator::StripeLocation* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_downloadStripeWithHint_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::downloadStripeWithHint(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeLocation* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_downloadStripeWithHint_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeLocation>* FileSystem::Stub::AsyncdownloadStripeWithHintRaw(::grpc::ClientContext* context, const ::coordinator::StripeIdWithHint& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_downloadStripeWithHint_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeLocation>* FileSystem::Stub::PrepareAsyncdownloadStripeWithHintRaw(::grpc::ClientContext* context, const ::coordinator::StripeIdWithHint& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_downloadStripeWithHint_, context, request, false);
}

::grpc::Status FileSystem::Stub::deleteStripe(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_deleteStripe_, context, request, response);
}

void FileSystem::Stub::experimental_async::deleteStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_deleteStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::deleteStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_deleteStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::deleteStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_deleteStripe_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::deleteStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_deleteStripe_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsyncdeleteStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_deleteStripe_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsyncdeleteStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_deleteStripe_, context, request, false);
}

::grpc::Status FileSystem::Stub::uploadCheck(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_uploadCheck_, context, request, response);
}

void FileSystem::Stub::experimental_async::uploadCheck(::grpc::ClientContext* context, const ::coordinator::StripeInfo* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_uploadCheck_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::uploadCheck(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_uploadCheck_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::uploadCheck(::grpc::ClientContext* context, const ::coordinator::StripeInfo* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_uploadCheck_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::uploadCheck(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_uploadCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsyncuploadCheckRaw(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_uploadCheck_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsyncuploadCheckRaw(::grpc::ClientContext* context, const ::coordinator::StripeInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_uploadCheck_, context, request, false);
}

::grpc::Status FileSystem::Stub::reportblockupload(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_reportblockupload_, context, request, response);
}

void FileSystem::Stub::experimental_async::reportblockupload(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_reportblockupload_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::reportblockupload(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_reportblockupload_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::reportblockupload(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_reportblockupload_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::reportblockupload(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_reportblockupload_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsyncreportblockuploadRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_reportblockupload_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsyncreportblockuploadRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_reportblockupload_, context, request, false);
}

::grpc::Status FileSystem::Stub::listStripe(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::coordinator::StripeLocation* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_listStripe_, context, request, response);
}

void FileSystem::Stub::experimental_async::listStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeLocation* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_listStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::listStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeLocation* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_listStripe_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::listStripe(::grpc::ClientContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeLocation* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_listStripe_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::listStripe(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::StripeLocation* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_listStripe_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeLocation>* FileSystem::Stub::AsynclistStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_listStripe_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::StripeLocation>* FileSystem::Stub::PrepareAsynclistStripeRaw(::grpc::ClientContext* context, const ::coordinator::StripeId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_listStripe_, context, request, false);
}

::grpc::ClientReader< ::coordinator::StripeLocation>* FileSystem::Stub::listAllStripesRaw(::grpc::ClientContext* context, const ::coordinator::ListAllStripeCMD& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), rpcmethod_listAllStripes_, context, request);
}

void FileSystem::Stub::experimental_async::listAllStripes(::grpc::ClientContext* context, ::coordinator::ListAllStripeCMD* request, ::grpc::experimental::ClientReadReactor< ::coordinator::StripeLocation>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::coordinator::StripeLocation>::Create(stub_->channel_.get(), stub_->rpcmethod_listAllStripes_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::coordinator::StripeLocation>* FileSystem::Stub::AsynclistAllStripesRaw(::grpc::ClientContext* context, const ::coordinator::ListAllStripeCMD& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_listAllStripes_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::coordinator::StripeLocation>* FileSystem::Stub::PrepareAsynclistAllStripesRaw(::grpc::ClientContext* context, const ::coordinator::ListAllStripeCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::coordinator::StripeLocation>::Create(channel_.get(), cq, rpcmethod_listAllStripes_, context, request, false, nullptr);
}

::grpc::Status FileSystem::Stub::transitionup(::grpc::ClientContext* context, const ::coordinator::TransitionUpCMD& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_transitionup_, context, request, response);
}

void FileSystem::Stub::experimental_async::transitionup(::grpc::ClientContext* context, const ::coordinator::TransitionUpCMD* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_transitionup_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::transitionup(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_transitionup_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::transitionup(::grpc::ClientContext* context, const ::coordinator::TransitionUpCMD* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_transitionup_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::transitionup(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_transitionup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsynctransitionupRaw(::grpc::ClientContext* context, const ::coordinator::TransitionUpCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_transitionup_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsynctransitionupRaw(::grpc::ClientContext* context, const ::coordinator::TransitionUpCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_transitionup_, context, request, false);
}

::grpc::Status FileSystem::Stub::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementPolicyCMD& request, ::coordinator::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_setplacementpolicy_, context, request, response);
}

void FileSystem::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementPolicyCMD* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, std::move(f));
}

void FileSystem::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::coordinator::SetPlacementPolicyCMD* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, reactor);
}

void FileSystem::Stub::experimental_async::setplacementpolicy(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::coordinator::RequestResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_setplacementpolicy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::AsyncsetplacementpolicyRaw(::grpc::ClientContext* context, const ::coordinator::SetPlacementPolicyCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_setplacementpolicy_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::coordinator::RequestResult>* FileSystem::Stub::PrepareAsyncsetplacementpolicyRaw(::grpc::ClientContext* context, const ::coordinator::SetPlacementPolicyCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::coordinator::RequestResult>::Create(channel_.get(), cq, rpcmethod_setplacementpolicy_, context, request, false);
}

FileSystem::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::Path, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::createDir), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeInfo, ::coordinator::StripeDetail>(
          std::mem_fn(&FileSystem::Service::uploadStripe), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeId, ::coordinator::StripeDetail>(
          std::mem_fn(&FileSystem::Service::downloadStripe), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeIdWithHint, ::coordinator::StripeLocation>(
          std::mem_fn(&FileSystem::Service::downloadStripeWithHint), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeId, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::deleteStripe), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeInfo, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::uploadCheck), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeId, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::reportblockupload), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::StripeId, ::coordinator::StripeLocation>(
          std::mem_fn(&FileSystem::Service::listStripe), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileSystem::Service, ::coordinator::ListAllStripeCMD, ::coordinator::StripeLocation>(
          std::mem_fn(&FileSystem::Service::listAllStripes), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::TransitionUpCMD, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::transitionup), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::coordinator::SetPlacementPolicyCMD, ::coordinator::RequestResult>(
          std::mem_fn(&FileSystem::Service::setplacementpolicy), this)));
}

FileSystem::Service::~Service() {
}

::grpc::Status FileSystem::Service::createDir(::grpc::ServerContext* context, const ::coordinator::Path* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::uploadStripe(::grpc::ServerContext* context, const ::coordinator::StripeInfo* request, ::coordinator::StripeDetail* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::downloadStripe(::grpc::ServerContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeDetail* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::downloadStripeWithHint(::grpc::ServerContext* context, const ::coordinator::StripeIdWithHint* request, ::coordinator::StripeLocation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::deleteStripe(::grpc::ServerContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::uploadCheck(::grpc::ServerContext* context, const ::coordinator::StripeInfo* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::reportblockupload(::grpc::ServerContext* context, const ::coordinator::StripeId* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::listStripe(::grpc::ServerContext* context, const ::coordinator::StripeId* request, ::coordinator::StripeLocation* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::listAllStripes(::grpc::ServerContext* context, const ::coordinator::ListAllStripeCMD* request, ::grpc::ServerWriter< ::coordinator::StripeLocation>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::transitionup(::grpc::ServerContext* context, const ::coordinator::TransitionUpCMD* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileSystem::Service::setplacementpolicy(::grpc::ServerContext* context, const ::coordinator::SetPlacementPolicyCMD* request, ::coordinator::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


std::unique_ptr< FromDataNode::Stub> FromDataNode::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FromDataNode::Stub> stub(new FromDataNode::Stub(channel));
  return stub;
}

FromDataNode::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel){}

FromDataNode::Service::Service() {
}

FromDataNode::Service::~Service() {
}


}  // namespace coordinator

